#服务器端口
server:
  port : 8088

#mysql配置
spring:
  #application-dev.yml或者#application-prod.yml配置文件选择
  profiles:
    active: @mvn.profile@
  application:
    name: base
#jwt
jwt:
  expire-time: 300000 #//5*60*1000 token到期时间5分钟，毫秒为单位
  refresh-expire-time: 1800 #// 30 * 60 RefreshToken到期时间为30分钟，秒为单位
  token-secret: "ljdyaishijin**3nkjnj??"

#mybatis plus
mybatis:
  packagename: com.hebut.base
  entity-vo: entity.vo
  auther: cxc

#swagger自定义
swagger:
  base:
    # 扫描的包，多个包使用逗号隔开
    package: com.hebut.base.controller
  contact:
    email: 1371491803@qq.com
    name: cxc
    url: 1371491803@qq.com
  description: 风电场管理
  title: ${spring.application.name} API Document
  url: localhost:${server.port}/doc.html
  version: 1.0.0
#knife4j作为swagger增强,地址：localhoet:8088/doc.html
knife4j:
  enable: ${swagger.enable}
  openapi:
    title: Knife4j官方文档

